/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMovementsRouteImport } from './routes/app/movements'
import { Route as AppCategoriesIndexRouteImport } from './routes/app/categories/index'
import { Route as AppMovementsCreateIncomeRouteImport } from './routes/app/movements/create/income'
import { Route as AppMovementsCreateExpenseRouteImport } from './routes/app/movements/create/expense'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsCreateIncomeRoute =
  AppMovementsCreateIncomeRouteImport.update({
    id: '/create/income',
    path: '/create/income',
    getParentRoute: () => AppMovementsRoute,
  } as any)
const AppMovementsCreateExpenseRoute =
  AppMovementsCreateExpenseRouteImport.update({
    id: '/create/expense',
    path: '/create/expense',
    getParentRoute: () => AppMovementsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/movements': typeof AppMovementsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/movements/create/expense': typeof AppMovementsCreateExpenseRoute
  '/app/movements/create/income': typeof AppMovementsCreateIncomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/movements': typeof AppMovementsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/movements/create/expense': typeof AppMovementsCreateExpenseRoute
  '/app/movements/create/income': typeof AppMovementsCreateIncomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/movements': typeof AppMovementsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/movements/create/expense': typeof AppMovementsCreateExpenseRoute
  '/app/movements/create/income': typeof AppMovementsCreateIncomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/movements'
    | '/app/'
    | '/auth/'
    | '/app/categories'
    | '/app/movements/create/expense'
    | '/app/movements/create/income'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/movements'
    | '/app'
    | '/auth'
    | '/app/categories'
    | '/app/movements/create/expense'
    | '/app/movements/create/income'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/movements'
    | '/app/'
    | '/auth/'
    | '/app/categories/'
    | '/app/movements/create/expense'
    | '/app/movements/create/income'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/': {
      id: '/app/categories/'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements/create/income': {
      id: '/app/movements/create/income'
      path: '/create/income'
      fullPath: '/app/movements/create/income'
      preLoaderRoute: typeof AppMovementsCreateIncomeRouteImport
      parentRoute: typeof AppMovementsRoute
    }
    '/app/movements/create/expense': {
      id: '/app/movements/create/expense'
      path: '/create/expense'
      fullPath: '/app/movements/create/expense'
      preLoaderRoute: typeof AppMovementsCreateExpenseRouteImport
      parentRoute: typeof AppMovementsRoute
    }
  }
}

interface AppMovementsRouteChildren {
  AppMovementsCreateExpenseRoute: typeof AppMovementsCreateExpenseRoute
  AppMovementsCreateIncomeRoute: typeof AppMovementsCreateIncomeRoute
}

const AppMovementsRouteChildren: AppMovementsRouteChildren = {
  AppMovementsCreateExpenseRoute: AppMovementsCreateExpenseRoute,
  AppMovementsCreateIncomeRoute: AppMovementsCreateIncomeRoute,
}

const AppMovementsRouteWithChildren = AppMovementsRoute._addFileChildren(
  AppMovementsRouteChildren,
)

interface AppRouteChildren {
  AppMovementsRoute: typeof AppMovementsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMovementsRoute: AppMovementsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
