/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/app/categories/index'
import { Route as AppCategoriesNewRouteImport } from './routes/app/categories/new'
import { Route as AppCategoriesIdIndexRouteImport } from './routes/app/categories/$id/index'
import { Route as AppCategoriesIdEditRouteImport } from './routes/app/categories/$id/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesNewRoute = AppCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIdIndexRoute = AppCategoriesIdIndexRouteImport.update({
  id: '/categories/$id/',
  path: '/categories/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIdEditRoute = AppCategoriesIdEditRouteImport.update({
  id: '/categories/$id/edit',
  path: '/categories/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app/categories/new': typeof AppCategoriesNewRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/categories/$id/edit': typeof AppCategoriesIdEditRoute
  '/app/categories/$id': typeof AppCategoriesIdIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app/categories/new': typeof AppCategoriesNewRoute
  '/app/categories': typeof AppCategoriesIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
  '/app/categories/$id/edit': typeof AppCategoriesIdEditRoute
  '/app/categories/$id': typeof AppCategoriesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/app/categories/new': typeof AppCategoriesNewRoute
  '/app/categories/': typeof AppCategoriesIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
  '/app/categories/$id/edit': typeof AppCategoriesIdEditRoute
  '/app/categories/$id/': typeof AppCategoriesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/app/categories/new'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/categories/$id/edit'
    | '/app/categories/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/app/categories/new'
    | '/app/categories'
    | '/app/dashboard'
    | '/app/categories/$id/edit'
    | '/app/categories/$id'
  id:
    | '__root__'
    | '/app'
    | '/auth'
    | '/auth/login'
    | '/auth/logout'
    | '/app/categories/new'
    | '/app/categories/'
    | '/app/dashboard/'
    | '/app/categories/$id/edit'
    | '/app/categories/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/': {
      id: '/app/categories/'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/new': {
      id: '/app/categories/new'
      path: '/categories/new'
      fullPath: '/app/categories/new'
      preLoaderRoute: typeof AppCategoriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/$id/': {
      id: '/app/categories/$id/'
      path: '/categories/$id'
      fullPath: '/app/categories/$id'
      preLoaderRoute: typeof AppCategoriesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories/$id/edit': {
      id: '/app/categories/$id/edit'
      path: '/categories/$id/edit'
      fullPath: '/app/categories/$id/edit'
      preLoaderRoute: typeof AppCategoriesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesNewRoute: typeof AppCategoriesNewRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppCategoriesIdEditRoute: typeof AppCategoriesIdEditRoute
  AppCategoriesIdIndexRoute: typeof AppCategoriesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesNewRoute: AppCategoriesNewRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppCategoriesIdEditRoute: AppCategoriesIdEditRoute,
  AppCategoriesIdIndexRoute: AppCategoriesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
