import type { Category } from "../types/categories";

export const listCategories = async (): Promise<Category[]> => {
  await new Promise((resolve) => setTimeout(resolve, 300));

  const mockData: Category[] = [
    {
      id: "1",
      name: "Salary",
      description: "Monthly fixed income.",
      kind: "income",
      icon: "dollar-sign",
      color: "green",
      status: "active",
    },
    {
      id: "2",
      name: "Rent",
      description: "Housing expenses.",
      kind: "expense",
      icon: "home",
      color: "blue",
      status: "active",
    },
    {
      id: "3",
      name: "Freelance",
      description: "Punctual work.",
      kind: "income",
      icon: "briefcase",
      color: "purple",
      status: "inactive",
    },
    {
      id: "4",
      name: "Supermarket",
      description: "Supermarket and food.",
      kind: "expense",
      icon: "shopping-cart",
      color: "orange",
      status: "active",
    },
    {
      id: "5",
      name: "Entertainment",
      description: "Movies, games, and hobbies.",
      kind: "expense",
      icon: "shopping-cart",
      color: "purple",
      status: "active",
    },
    {
      id: "6",
      name: "Utilities",
      description: "Electricity, water, internet.",
      kind: "expense",
      icon: "home",
      color: "blue",
      status: "active",
    },
    {
      id: "7",
      name: "Transportation",
      description: "Fuel, public transport, rides.",
      kind: "expense",
      icon: "shopping-cart",
      color: "orange",
      status: "active",
    },
    {
      id: "8",
      name: "Health",
      description: "Medical and pharmacy expenses.",
      kind: "expense",
      icon: "home",
      color: "purple",
      status: "active",
    },
    {
      id: "9",
      name: "Subscription",
      description: "Streaming and software subscriptions.",
      kind: "expense",
      icon: "shopping-cart",
      color: "blue",
      status: "active",
    },
    {
      id: "10",
      name: "Investment",
      description: "Stocks, crypto, and funds.",
      kind: "income",
      icon: "briefcase",
      color: "green",
      status: "active",
    },
    {
      id: "11",
      name: "Bonus",
      description: "Work bonuses and incentives.",
      kind: "income",
      icon: "dollar-sign",
      color: "green",
      status: "active",
    },
    {
      id: "12",
      name: "Gifts",
      description: "Gifts and special occasions.",
      kind: "expense",
      icon: "home",
      color: "orange",
      status: "active",
    },
    {
      id: "13",
      name: "Education",
      description: "Courses and learning materials.",
      kind: "expense",
      icon: "briefcase",
      color: "purple",
      status: "active",
    },
    {
      id: "14",
      name: "Restaurant",
      description: "Meals and dining out.",
      kind: "expense",
      icon: "shopping-cart",
      color: "blue",
      status: "active",
    },
    {
      id: "15",
      name: "Insurance",
      description: "Health, car, and home insurance.",
      kind: "expense",
      icon: "home",
      color: "green",
      status: "active",
    },
    {
      id: "16",
      name: "Gym",
      description: "Fitness and wellness.",
      kind: "expense",
      icon: "briefcase",
      color: "orange",
      status: "inactive",
    },
    {
      id: "17",
      name: "Consulting",
      description: "Professional consulting work.",
      kind: "income",
      icon: "briefcase",
      color: "green",
      status: "active",
    },
    {
      id: "18",
      name: "Clothing",
      description: "Clothes and accessories.",
      kind: "expense",
      icon: "shopping-cart",
      color: "purple",
      status: "active",
    },
    {
      id: "19",
      name: "Travel",
      description: "Flights, hotels, and trips.",
      kind: "expense",
      icon: "briefcase",
      color: "blue",
      status: "active",
    },
    {
      id: "20",
      name: "Pet Care",
      description: "Pet food and veterinary care.",
      kind: "expense",
      icon: "home",
      color: "orange",
      status: "active",
    },
  ];

  return mockData;
};

// import { api } from "@/lib/api-client";
//
// export const listCategories = async (
// ): Promise<Category[]> => {
//   const response = await api.get<Category[]>("/v1/categories", {
//     params,
//   });
//   return response.data;
// };
